
####################################################################################
# Generated by Vivado 2025.1 built on 'Wed May 21 22:58:25 MDT 2025' by 'xbuild'
# Command Used: write_xdc -force /media/ekhafagy/Data2/Vivado/project_2/constrs_1.xdc
####################################################################################


####################################################################################
# Constraints from file : 'design_1_clk_wiz_1_0.xdc'
####################################################################################

#current_instance design_1_i/clk_wiz_1/inst
#set_property PHASESHIFT_MODE LATENCY [get_cells -hierarchical *adv*]

#####################################################################################
## Constraints from file : 'design_1_clk_wiz_1_0_board.xdc'
#####################################################################################

##--------------------Physical Constraints-----------------

#current_instance -quiet
#set_property BOARD_PART_PIN som240_1_a6 [get_ports som240_1_connector_hpa_clk0p_clk]
#set_property IOSTANDARD LVCMOS18 [get_ports som240_1_connector_hpa_clk0p_clk]
#set_property PCB_MIN_DELAY 0.36703 [get_ports som240_1_connector_hpa_clk0p_clk]
#set_property PCB_MAX_DELAY 0.44859 [get_ports som240_1_connector_hpa_clk0p_clk]
#set_property PACKAGE_PIN C3 [get_ports som240_1_connector_hpa_clk0p_clk]


####################################################################################
# Constraints from file : 'design_1_clk_wiz_1_0.xdc'
####################################################################################


# file: design_1_clk_wiz_1_0.xdc
# (c) Copyright 2017-2018, 2023 Advanced Micro Devices, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of AMD and is protected under U.S. and international copyright
# and other intellectual property laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# AMD, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) AMD shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or AMD had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# AMD products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of AMD products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
#create_clock -period 40.000 [get_ports som240_1_connector_hpa_clk0p_clk]
#set_input_jitter [get_clocks -of_objects [get_ports som240_1_connector_hpa_clk0p_clk]] 0.400




####################################################################################
# Constraints from file : 'design_1_rst_clk_wiz_1_100M_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------

####################################################################################
# USER DEFINED LEDS
####################################################################################

####################################################################################
# Constraints from file : 'design_1_axi_gpio_0_1_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------

set_property BOARD_PART_PIN som240_1_d13 [get_ports {som240_1_connector_User_led_tri_o[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {som240_1_connector_User_led_tri_o[0]}]
set_property PCB_MIN_DELAY 0.36439 [get_ports {som240_1_connector_User_led_tri_o[0]}]
set_property PCB_MAX_DELAY 0.44537 [get_ports {som240_1_connector_User_led_tri_o[0]}]
set_property PACKAGE_PIN F8 [get_ports {som240_1_connector_User_led_tri_o[0]}]

set_property BOARD_PART_PIN som240_1_d14 [get_ports {som240_1_connector_User_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {som240_1_connector_User_led_tri_o[1]}]
set_property PCB_MIN_DELAY 0.36428 [get_ports {som240_1_connector_User_led_tri_o[1]}]
set_property PCB_MAX_DELAY 0.44523 [get_ports {som240_1_connector_User_led_tri_o[1]}]
set_property PACKAGE_PIN E8 [get_ports {som240_1_connector_User_led_tri_o[1]}]



#####################################################################################
## Constraints from file : 'bd_afc3_psr_aclk_0_board.xdc'
#####################################################################################

##--------------------Physical Constraints-----------------



#####################################################################################
## Constraints from file : 'smartconnect.xdc'
#####################################################################################

## -----------------------SMC Waivers--------------------


#####################################################################################
## Constraints from file : 'design_1_microblaze_0_0.xdc'
#####################################################################################

#current_instance design_1_i/microblaze_0/U0
#set_false_path -through [get_ports -scoped_to_current_instance Reset]

## Waiver for asynchronous reset
#create_waiver -type CDC -id {CDC-10} -user "microblaze" -desc "Asynchronous reset" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/Reset_DFF/Synchronize.use_sync_reset.sync_reg[1]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"

## Waivers for debug interface
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.capture_1_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.data_read_reg_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.instr_read_reg_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.shift_count_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.status_reg_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.Instr_Insert_Reg_En_1_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Dbg_Instr*_TCK_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.unchanged_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.command_reg_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_TClk_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.control_reg_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_TClk_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_TClk_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.single_Step_TClk_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.Instr_Insert_Reg_En_1_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.new_dbg_instr_shifting_CLK_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Instr_Reg_TCK_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Instr_Reg_TCK_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.control_reg_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.instr_read_reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.status_reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/running_clock_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_running_clock/Single_Synchronize.use_async_reset.sync_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_sleep/Single_Synchronize.use_async_reset.sync_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/*Debug_Control.dbg_brki_hit_reg*/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_dbg_brk_hit/Single_Synchronize.use_async_reset.sync_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/*Debug_Control.dbg_hit_reg[*]/C}] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_dbg_hit/sync_bits*.sync_bit/Single_Synchronize.use_async_reset.sync_reg*/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.shift_datain_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-4} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/data_rd_reg_reg[*]/C}] -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.data_read_reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.capture_1_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/running_clock_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/command_reg_clear_reg/C] -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.command_reg_reg[*]/CLR}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/start_single_step_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.single_Step_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_cmd_i_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_cmd_i_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Instr_Reg_TCK_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.command_reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_TClk_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.control_reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_TClk_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_TClk_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.single_Step_TClk_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.control_reg_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/command_reg_clear_reg/C] -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.command_reg_reg[*]/CLR}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.continue_from_brk_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_cmd_i_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.force_stop_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_cmd_i_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.normal_stop_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/start_single_step_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.single_Step_TClk_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Instr_Reg_TCK_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.New_Instr_Reg_TCK_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [list [get_pins { MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[0].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[1].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[2].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[3].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[4].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[5].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[6].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[7].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK }]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-10} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [list [get_pins { MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[0].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[1].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[2].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[3].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[4].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[5].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[6].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[7].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK }]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [list [get_pins { MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[0].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[1].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[2].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[3].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[4].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[5].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[6].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[7].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK }]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [list [get_pins { MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[0].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[1].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[2].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[3].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[4].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[5].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[6].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[7].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/D }]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [list [get_pins { MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[0].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[1].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[2].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[3].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[4].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[5].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[6].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK MicroBlaze_Core_I/Performance.Core/Use_Debug_Logic.Master_Core.Debug_Perf/Using_PC_Breakpoints.All_PC_Brks[0].Serial_Interface_1.address_hit_I/Compare[7].SRLC16E_I/Use_unisim.MB_SRL16CE_I1/CLK }]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/Performance.Core/Decode_I/ex_sleep_i_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_sleep/Single_Synchronize.use_async_reset.sync_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "microblaze" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/*Debug_Control.dbg_stop_instr_fetch_nohalt_reg/C] -to [get_pins -quiet MicroBlaze_Core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.sync_stop_CPU/Single_Synchronize.use_async_reset.sync_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"


#####################################################################################
## Constraints from file : 'design_1_mdm_1_1.xdc'
#####################################################################################

## file: design_1_mdm_1_1.xdc
#current_instance -quiet
#current_instance design_1_i/mdm_1/U0
#create_clock -period 33.333 [get_pins Use*.BSCAN*/*/INTERNAL_TCK]
#create_generated_clock -source [get_pins Use*.BSCAN*/*/INTERNAL_TCK] -divide_by 2 [get_pins Use*.BSCAN*/*/UPDATE]
#create_generated_clock -source [get_pins Use*.BSCAN*/*/INTERNAL_TCK] -divide_by 1 [get_pins Use*.BSCAN*/*/DRCK]
#set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/INTERNAL_TCK]]
#set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/UPDATE]]
#set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/DRCK]]
#set_input_delay -clock [get_clocks -of_objects [get_pins Use*.BSCAN*/*/DRCK]] 1.000 [get_pins Use*.BSCAN*/*/INTERNAL_TDI]

#create_waiver -type CDC -id {CDC-10} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Debug_SYS_Rst_i_reg/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"

## Methodology waivers for internal BSCAN clock constraints
#create_waiver -type METHODOLOGY -id {TIMING-54} -user "mdm" -desc "Avoid warning for valid DRCK clock constraint" -tags "12436" -scope -internal -objects [get_clocks -quiet -of_objects [get_pins Use*.BSCAN*/*/DRCK]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type METHODOLOGY -id {TIMING-54} -user "mdm" -desc "Avoid warning for valid UPDATE clock constraint" -tags "12436" -scope -internal -objects [get_clocks -quiet -of_objects [get_pins Use*.BSCAN*/*/UPDATE]] -timestamp "Sat Jul 18 12:33:25 GMT 2026"

## Waivers for serial debug interface
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.completion*reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.mb_data_overrun_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.mb_instr_error_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.mb_instr_overrun_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.*sample*_reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.*count_reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.completion_block_reg/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.completion*reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_Serial_Unified_Completion.*count_reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"

## Waivers for BSCAN
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.TDI_Shifter_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/sel_n_reg/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/shift_Count_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/tdi_shifter_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/command_1_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Debug_Rst_i_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Debug_SYS_Rst_i_reg/CE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.command_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.command_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/completion_ctrl_reg[0]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.FDC_I/Using_FPGA*.Native/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/tdi_shifter_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.TDI_Shifter_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-2} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.PORT_Selector*_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-2} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.Config_Reg_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-2} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-4} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.PORT_Selector_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/sel_n_reg/PRE] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.Config_Reg_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.TDI_Shifter_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/sel_n_reg/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-8} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-10} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.PORT_Selector*_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-10} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-10} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-11} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/*] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-11} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.PORT_Selector*_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/TDO] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TDI] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/Use_BSCAN.Config_Reg_reg*/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.FDC_I/Using_FPGA*.Native/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.command_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/command_1_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Debug_Rst_i_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Debug_SYS_Rst_i_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.FDC_I/Using_FPGA*.Native/C] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/Use_BSCAN.PORT_Selector*_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_BSCAN.command_reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"

## Waivers for UART
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.tdo_reg_reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.fifo*reg[*]/*}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_UART.tx_buffered_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_UART.execute_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_UART.fifo_*_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-1} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.tdo_reg_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-7} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_UART.execute_reg/CLR] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.fifo_Din_reg[*]/CE}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-13} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -from [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.fifo_Din_reg[*]/C}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet {MDM_Core_I1/JTAG_CONTROL_I/Use_UART.fifo*reg[*]/D}] -timestamp "Sat Jul 18 12:33:25 GMT 2026"
#create_waiver -type CDC -id {CDC-15} -user "mdm" -desc "Debug protocol ensures stable signals" -tags "12436" -scope -internal -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/Use_UART.tx_buffered_reg/D] -timestamp "Sat Jul 18 12:33:25 GMT 2026"


#####################################################################################
## Constraints from file : 'xpm_cdc_array_single.tcl'
#####################################################################################

## Scoped constraints for xpm_cdc_array_single



#####################################################################################
## Constraints from file : 'xpm_cdc_async_rst.tcl'
#####################################################################################

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_exit_pipeline/m01_exit/inst/xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_nodes/m01_ar_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_nodes/m01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_nodes/m01_b_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_nodes/m01_r_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m01_nodes/m01_w_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/switchboards/i_nodes/i_ar_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/switchboards/i_nodes/i_aw_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/switchboards/i_nodes/i_b_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/switchboards/i_nodes/i_r_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/switchboards/i_nodes/i_w_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]

## Scoped constraints for xpm_cdc_async_rst

## Scoped constraints for xpm_cdc_async_rst
#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst
#set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]


#####################################################################################
## Constraints from file : 'xpm_cdc_single.tcl'
#####################################################################################

## Scoped constraints for xpm_cdc_single

#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX
#set_false_path -to [get_cells {syncstages_ff_reg[0]}]


## Scoped constraints for xpm_cdc_single

#current_instance -quiet
#current_instance design_1_i/axi_smc/inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT
#set_false_path -to [get_cells {syncstages_ff_reg[0]}]


## Scoped constraints for xpm_cdc_single

#current_instance -quiet
#current_instance design_1_i/rst_clk_wiz_1_100M/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX
#set_false_path -to [get_cells {syncstages_ff_reg[0]}]


## Scoped constraints for xpm_cdc_single

#current_instance -quiet
#current_instance design_1_i/rst_clk_wiz_1_100M/U0/EXT_LPF/ACTIVE_HIGH_EXT.ACT_HI_EXT
#set_false_path -to [get_cells {syncstages_ff_reg[0]}]



## Vivado Generated miscellaneous constraints

##revert back to original instance
#current_instance -quiet
